### ISSUE TITLE
Better pragma detection

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/danger-plugin-flow#3]
Right now this plugin basically just checks that the string `@flow` exists anywhere in the file. Instead of doing that we should be using the same logic Flow uses internally to determine whether to check a file or not.

/cc @calebmer is there a list of rules/heuristics that Flow uses to determine whether to include a file or not?

**Comment by kevinSuttle** [comment]
Maybe this will help narrow the scope: 

After seeing these two docs stating that the pragma needs to be [before any JS](https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow) and can't be [below line 10](https://flow.org/en/docs/config/options/#toc-max-header-tokens-integer), I [found some files](https://superuser.com/questions/1303763/find-files-that-contain-a-string-but-not-on-the-correct-line) in a project that didn't have it in the right place.

**Comment by kevinSuttle** [comment]
Threw this together quickly: https://repl.it/repls/NotedSalmonFlashdrive

**Comment by mxstbr** [comment]
That looks perfect! Wanna submit a PR adding that to the repo? This is the line that needs to be replaced: https://github.com/withspectrum/danger-plugin-flow/blob/915bb78d8119b510368f4da3a2372eaff679bf89/src/index.ts#L50

with something like `const unflowedFiles = files.filter(({ content }) => detectFlowPragma(content)).map(({ path }) => path)`

**Comment by kevinSuttle** [comment]
I can give it a shot 👍🏼
