### ISSUE TITLE
Support danger local 

### ISSUE THREAD

**Issue by jakubzitny** [withspectrum/danger-plugin-flow#38]
Currently, `danger-plugin-flow` is locked to GitHub, because it uses [danger.github](https://github.com/withspectrum/danger-plugin-flow/blob/master/src/index.ts#L43) object for getting the contents of changed files.

It would be cool to generalize this to `danger local` run (which will ensure it works for other services and unsupported CIs (e.g. GitLab) as well).

**Comment by mxstbr** [comment]
Very open to PRs!
